# Generated by Django 2.1 on 2020-08-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200802_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='text',
        ),
    ]
